site_name: JustAnotherBlog
theme:
  name: material
  palette: 
    - scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to Dark Mode
    - scheme: slate
      toggle: 
        icon: material/brightness-4
        name: Switch to Light Mode
  
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - search
  - glightbox
  - blog:
      archive_date_format: yyyy
      archive_toc: false
      authors: false
      blog_dir: .
      blog_toc: true
      draft_if_future_date: true
  - tags: 
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jpboyce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jpboyce/
  consent:
    title: Cookie consent
    description: >-
      This website uses cookies to ensure you get the best experience on our website.

